### ISSUE TITLE
what is the difference between this iLO and above iDRAC when rebooting ?

### ISSUE THREAD

**Issue by glimchb** [opiproject/lab#43]
what is the difference between this iLO and above iDRAC when rebooting ?

_Originally posted by @glimchb in https://github.com/opiproject/lab/pull/42#discussion_r1677224472_

**Comment by Sakethanne** [comment]
The bios.yml Ansible playbook requires separate sections for iDRAC to reboot and apply the BIOS configurations to the DPUs from DELL(DH1 and DH4 respectively) and iLO to reboot and apply the BIOS configurations to the DPUs from HP(DH3 and DH4 respectively). 

There is a slight difference in operation of the both iDRAC and iLO, where iDRAC requires a BIOS configuration job must be created before rebooting to ensure that any changes to the BIOS settings are applied correctly whereas iLO doesnot require such a configuration task. 

More details can be found in their documentations at: https://dl.dell.com/topicspdf/44010ug_en-us.pdf and https://support.hpe.com/hpesc/public/docDisplay?docId=a00105236en_us&docLocale=en_US&page=index.html
