### ISSUE TITLE
ansible(bios): Bios configuration unable to run from Semaphore

### ISSUE THREAD

**Issue by Sakethanne** [opiproject/lab#57]
FAILED! => {"ansible_facts": {}, "changed": false, "failed_modules": {"ansible.legacy.setup": {"ansible_facts": {"discovered_interpreter_python": "/usr/bin/python3.11"}, "failed": true, "module_stderr": "/bin/sh: sudo: not found\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 127, "warnings": ["Platform linux on host dh1bmc is using the discovered Python interpreter at /usr/bin/python3.11, but future installation of another Python interpreter could change the meaning of that path. See https://docs.ansible.com/ansible-core/2.14/reference_appendices/interpreter_discovery.html for more information."]}}, "msg": "The following modules failed to execute: ansible.legacy.setup\n"}

**Comment by glimchb** [comment]
Dup with #6
